version: "3.8"
services: 
  app_react:
    build: ./myshoop/front_end
    container_name: app_react
    volumes:
      - build_myshoop:/var/www/html
    depends_on:
      - myshoop_server

  myshoop_server:
    container_name: myshoop_server
    build: ./myshoop/back_end
    env_file:
      - .env.example
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - myshoopDB
    volumes: 
      - ./back_end:/usr/src
      - /usr/src/node_modules
    entrypoint: dockerize -wait tcp://${POSTGRES_IMAGE_DB_DOCKER}:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run docker:dev:create"

  myshoopDB:
    image: postgres:13
    container_name: myshoopDB
    env_file:
      - .env.example
    ports:
      - 2345:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    restart: always
    volumes:
      - progresDB:/data/postgres

  nginx:
    build: ./myshoop/nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_myshoop:/var/www/html
    depends_on:
      - app_react

volumes:
  build_myshoop:
  progresDB:
