version: "3.8"
services: 
  app_react:
    build: ./myshoop/front_end
    container_name: app_react
    volumes:
      - build_myshoop:/var/www/html
    depends_on:
      - myshoop_server

  myshoop_server:
    container_name: myshoop_server
    build: ./myshoop/back_end
    env_file:
      - .env.example
    ports:
      - 4000:$4000
    depends_on:
      - myshoopDB
    entrypoint: dockerize -wait tcp://myshoopDB:5432 -timeout 20s docker-entrypoint.sh
    command: "npm run docker:dev:create"

  myshoopDB:
    image: postgres:13
    container_name: myshoopDB
    env_file:
      - .env.example
    ports:
      - 2345:5432
    environment:
      - POSTGRES_PASSWORD=dd
      - POSTGRES_DB=myshoop
    restart: always
    volumes:
      - progresDB:/data/postgres

  nginx:
    build: ./myshoop/nginx
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - build_myshoop:/var/www/html
    depends_on:
      - app_react

volumes:
  build_myshoop:
  progresDB:
