version: '3'
services:
  app:
    container_name: myshoop
    build: .
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgresDB
    volumes:
      - .:/app/src

  postgresDB:
    image: postgres:13
    container_name: postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DATABASE}
    restart: always
    volumes:
      - progresDB:/data/postgres

volumes:
  app:
  progresDB:
