name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:
 
  build:

    runs-on: self-hosted
    env: 
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      HOMOLOGACAO_ROUT: ${{ secrets.HOMOLOGACAO_ROUT }}
      URL_GENET: ${{ secrets.URL_GENET }}
      
    steps:
    - uses: actions/checkout@v3
    - name: Clean all
      run:  sudo docker-compose -f "docker-compose.yml" down --volumes app_react --volumes myshoop_server 
    - name: Build the Docker image


      run: |
        sudo docker-compose -f "docker-compose.yml" up -d --build 
        echo "CLIENT_ID= $CLIENT_ID" > .env
        echo "CLIENT_SECRET= $CLIENT_SECRET" >> .env
        echo "HOMOLOGACAO_ROUT= $HOMOLOGACAO_ROUT" >> .env
        echo "URL_GENET= $URL_GENET" >> .env
        sudo docker cp .env myshoop_server:/app/.env
        sudo docker cp   ../../../../../chaves/homologacao-432132-dudu.p12 myshoop_server:/app/homologacao-432132-dudu.p12
