name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:

 
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Clean all
        
      run: |
        export POSTGRES_USERNAME=${{ secrets.POSTGRES_USERNAME }} 
        export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
        export POSTGRES_IMAGE_DB_DOCKER=${{ secrets.POSTGRES_IMAGE_DB_DOCKER }}
        export POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
        export POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }}
        export PORT=${{ secrets.PORT }}

        export DATABASE_URL=postgres://${{secrets.POSTGRES_USERNAME}}:${{secrets.POSTGRES_PASSWORD}}@${{secrets.POSTGRES_IMAGE_DB_DOCKER}}:${{secrets.POSTGRES_PORT}}/${{secrets.POSTGRES_DATABASE}}?schema=public

        export CLIENT_ID=${{secrets.POSTGRES_USERNAME}}
        export CLIENT_SECRET=${{secrets.POSTGRES_USERNAME}}
        export HOMOLOGACAO_ROUT=${{secrets.POSTGRES_USERNAME}}

        export URL_GENET=${{secrets.POSTGRES_USERNAME}}
    
        docker-compose -f "docker-compose.yml" down -v
    - name: Build the Docker image
      run: |
        export POSTGRES_USERNAME:${{ secrets.POSTGRES_USERNAME }} 
        export POSTGRES_PASSWORD:${{ secrets.POSTGRES_PASSWORD }}
        export POSTGRES_IMAGE_DB_DOCKER:${{ secrets.POSTGRES_IMAGE_DB_DOCKER }}
        export POSTGRES_PORT:${{ secrets.POSTGRES_PORT }}
        export POSTGRES_DATABASE:${{ secrets.POSTGRES_DATABASE }}
        export PORT:${{ secrets.PORT }}
  
        export DATABASE_URL:postgres://${{secrets.POSTGRES_USERNAME}}:${{secrets.POSTGRES_PASSWORD}}@${{secrets.POSTGRES_IMAGE_DB_DOCKER}}:${{secrets.POSTGRES_PORT}}/${{secrets.POSTGRES_DATABASE}}?schema=public
  
        export CLIENT_ID:${{secrets.POSTGRES_USERNAME}}
        export CLIENT_SECRET:${{secrets.POSTGRES_USERNAME}}
        export HOMOLOGACAO_ROUT:${{secrets.POSTGRES_USERNAME}}
  
        export URL_GENET:${{secrets.POSTGRES_USERNAME}}
    
        export docker-compose -f "docker-compose.yml" up -d --build
        
