name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:
 
  build:

    runs-on: self-hosted
  
    steps:
    - uses: actions/checkout@v3
    - name: Clean all
      run:  docker-compose -f "docker-compose.yml" down -v
    - name: Create .env file
      env: 
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        HOMOLOGACAO_ROUT: ${{ secrets.HOMOLOGACAO_ROUT }}
        URL_GENET: ${{ secrets.URL_GENET }}
      run: | 
          echo "POSTGRES_USERNAME=postgres" > .env
          echo "POSTGRES_PASSWORD=dd" >> .env
          echo "POSTGRES_IMAGE_DB_DOCKER=myshoopDB" >> .env
          echo "POSTGRES_PORT=5432" >> .env
          echo "POSTGRES_DATABASE=myshoop" >> .env
          echo "PORT=4000" >> .env
          
          echo "DATABASE_URL=postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_IMAGE_DB_DOCKER}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?schema=public" >> .env
          
          echo "CLIENT_ID =${{CLIENT_ID}}" >> .env
          echo "CLIENT_SECRET =${{CLIENT_SECRET}}" >> .env
          echo "HOMOLOGACAO_ROUT =${{HOMOLOGACAO_ROUT}}" >> .env
          
          echo "URL_GENET= ${{URL_GENET}}" >> .env

    - name: Copy .env file to container
      run: docker cp .env myshoop_server:/app/.env

    - name: Build the Docker image
      run: docker-compose -f "docker-compose.yml" up -d --build