name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:
 
  build:

    runs-on: self-hosted
    with: 
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      HOMOLOGACAO_ROUT: ${{ secrets.HOMOLOGACAO_ROUT }}
      URL_GENET: ${{ secrets.URL_GENET }}
      
    steps:
    - uses: actions/checkout@v3
    - name: Clean all
      run:  docker-compose -f "docker-compose.yml" down -v
    - name: Build the Docker image
    
      run: | 
          echo "POSTGRES_USERNAME=postgres" > .env.example
          echo "POSTGRES_PASSWORD=dd" >> .env.example
          echo "POSTGRES_IMAGE_DB_DOCKER=myshoopDB" >> .env.example
          echo "POSTGRES_PORT=5432" >> .env.example
          echo "POSTGRES_DATABASE=myshoop" >> .env.example
          echo "PORT=4000" >> .env.example
          
          echo "DATABASE_URL=postgres://${POSTGRES_USERNAME}:${POSTGRES_PASSWORD}@${POSTGRES_IMAGE_DB_DOCKER}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?schema=public" >> .env.example
          
          echo "CLIENT_ID =${{CLIENT_ID}}" >> .env.example
          echo "CLIENT_SECRET =${{CLIENT_SECRET}}" >> .env.example
          echo "HOMOLOGACAO_ROUT =${{HOMOLOGACAO_ROUT}}" >> .env.example
          
          echo "URL_GENET= ${{URL_GENET}}" >> .env.example

         docker cp .env.example myshoop_server:/app/.env.example
         docker-compose -f "docker-compose.yml" up -d --build