name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:
 
  build:

    runs-on: self-hosted
    env: 
      CLIENT_ID: ${{ secrets.CLIENT_ID }}
      CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
      HOMOLOGACAO_ROUT: ${{ secrets.HOMOLOGACAO_ROUT }}
      URL_GENET: ${{ secrets.URL_GENET }}
      
    steps:
    - uses: actions/checkout@v3
    - name: Clean all
      run:  docker-compose -f "docker-compose.yml" down -v
    - name: Build the Docker image
      
      run: |
        docker-compose -f "docker-compose.yml" up -d --build
        echo $CLIENT_ID > .UUUU
        echo $CLIENT_SECRET > .UUUU
        echo $HOMOLOGACAO_ROUT > .UUUU
        echo $URL_GENET > .UUUU
        docker cp .UUUU myshoop_server:/app/.UUUU
        