name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    
jobs:

 
  build:

    runs-on: self-hosted
      
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "PORT : ${{vars.PORT}}"
        docker-compose -f "docker-compose.yml" up -d --build 
        
